// Code generated by protoc-gen-go.
// source: proto.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	proto.proto

It has these top-level messages:
	Block
	BlockHeader
	Transaction
	Operation
	DepositOperation
	WithdrawOperation
	Address
	PublicKey
	Privatekey
	Signature
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OperationType int32

const (
	OperationType_Deposit  OperationType = 0
	OperationType_Withdraw OperationType = 1
)

var OperationType_name = map[int32]string{
	0: "Deposit",
	1: "Withdraw",
}
var OperationType_value = map[string]int32{
	"Deposit":  0,
	"Withdraw": 1,
}

func (x OperationType) String() string {
	return proto.EnumName(OperationType_name, int32(x))
}
func (OperationType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CryptoType int32

const (
	CryptoType_ECDSA CryptoType = 0
	CryptoType_RSA   CryptoType = 1
	CryptoType_DSA   CryptoType = 2
)

var CryptoType_name = map[int32]string{
	0: "ECDSA",
	1: "RSA",
	2: "DSA",
}
var CryptoType_value = map[string]int32{
	"ECDSA": 0,
	"RSA":   1,
	"DSA":   2,
}

func (x CryptoType) String() string {
	return proto.EnumName(CryptoType_name, int32(x))
}
func (CryptoType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Block struct {
	Header       *BlockHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Transactions []*Transaction `protobuf:"bytes,2,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type BlockHeader struct {
	Time      *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
	Number    int64                      `protobuf:"varint,2,opt,name=number" json:"number,omitempty"`
	Nance     []byte                     `protobuf:"bytes,3,opt,name=nance,proto3" json:"nance,omitempty"`
	PrevHash  []byte                     `protobuf:"bytes,4,opt,name=prevHash,proto3" json:"prevHash,omitempty"`
	CurrHash  []byte                     `protobuf:"bytes,5,opt,name=currHash,proto3" json:"currHash,omitempty"`
	Signature *Signature                 `protobuf:"bytes,6,opt,name=signature" json:"signature,omitempty"`
}

func (m *BlockHeader) Reset()                    { *m = BlockHeader{} }
func (m *BlockHeader) String() string            { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()               {}
func (*BlockHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BlockHeader) GetTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *BlockHeader) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Transaction struct {
	Operations []*Operation `protobuf:"bytes,1,rep,name=operations" json:"operations,omitempty"`
	Signatures []*Signature `protobuf:"bytes,2,rep,name=signatures" json:"signatures,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Transaction) GetOperations() []*Operation {
	if m != nil {
		return m.Operations
	}
	return nil
}

func (m *Transaction) GetSignatures() []*Signature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

type Operation struct {
	OpType  OperationType `protobuf:"varint,1,opt,name=opType,enum=protos.OperationType" json:"opType,omitempty"`
	Payload []byte        `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Operation) Reset()                    { *m = Operation{} }
func (m *Operation) String() string            { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()               {}
func (*Operation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DepositOperation struct {
	Receiver *Address `protobuf:"bytes,1,opt,name=receiver" json:"receiver,omitempty"`
	Amount   int64    `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
	Symbol   string   `protobuf:"bytes,3,opt,name=symbol" json:"symbol,omitempty"`
}

func (m *DepositOperation) Reset()                    { *m = DepositOperation{} }
func (m *DepositOperation) String() string            { return proto.CompactTextString(m) }
func (*DepositOperation) ProtoMessage()               {}
func (*DepositOperation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DepositOperation) GetReceiver() *Address {
	if m != nil {
		return m.Receiver
	}
	return nil
}

type WithdrawOperation struct {
	Sender *Address `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	Amount int64    `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
	Symbol string   `protobuf:"bytes,3,opt,name=symbol" json:"symbol,omitempty"`
}

func (m *WithdrawOperation) Reset()                    { *m = WithdrawOperation{} }
func (m *WithdrawOperation) String() string            { return proto.CompactTextString(m) }
func (*WithdrawOperation) ProtoMessage()               {}
func (*WithdrawOperation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *WithdrawOperation) GetSender() *Address {
	if m != nil {
		return m.Sender
	}
	return nil
}

type Address struct {
	AddressByte []byte `protobuf:"bytes,1,opt,name=addressByte,proto3" json:"addressByte,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type PublicKey struct {
	Type CryptoType `protobuf:"varint,1,opt,name=type,enum=protos.CryptoType" json:"type,omitempty"`
	Key  []byte     `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *PublicKey) Reset()                    { *m = PublicKey{} }
func (m *PublicKey) String() string            { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()               {}
func (*PublicKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type Privatekey struct {
	Type CryptoType `protobuf:"varint,1,opt,name=type,enum=protos.CryptoType" json:"type,omitempty"`
	Key  []byte     `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *Privatekey) Reset()                    { *m = Privatekey{} }
func (m *Privatekey) String() string            { return proto.CompactTextString(m) }
func (*Privatekey) ProtoMessage()               {}
func (*Privatekey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type Signature struct {
	Type CryptoType `protobuf:"varint,1,opt,name=type,enum=protos.CryptoType" json:"type,omitempty"`
	R    []byte     `protobuf:"bytes,2,opt,name=r,proto3" json:"r,omitempty"`
	S    []byte     `protobuf:"bytes,3,opt,name=s,proto3" json:"s,omitempty"`
}

func (m *Signature) Reset()                    { *m = Signature{} }
func (m *Signature) String() string            { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()               {}
func (*Signature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto.RegisterType((*Block)(nil), "protos.Block")
	proto.RegisterType((*BlockHeader)(nil), "protos.BlockHeader")
	proto.RegisterType((*Transaction)(nil), "protos.Transaction")
	proto.RegisterType((*Operation)(nil), "protos.Operation")
	proto.RegisterType((*DepositOperation)(nil), "protos.DepositOperation")
	proto.RegisterType((*WithdrawOperation)(nil), "protos.WithdrawOperation")
	proto.RegisterType((*Address)(nil), "protos.Address")
	proto.RegisterType((*PublicKey)(nil), "protos.PublicKey")
	proto.RegisterType((*Privatekey)(nil), "protos.Privatekey")
	proto.RegisterType((*Signature)(nil), "protos.Signature")
	proto.RegisterEnum("protos.OperationType", OperationType_name, OperationType_value)
	proto.RegisterEnum("protos.CryptoType", CryptoType_name, CryptoType_value)
}

func init() { proto.RegisterFile("proto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 534 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x8f, 0xd3, 0x30,
	0x14, 0xdc, 0x6c, 0xdb, 0xb4, 0x79, 0x09, 0x90, 0x35, 0x1f, 0x8a, 0x7a, 0xa1, 0xca, 0x01, 0x4a,
	0x2b, 0x52, 0xb1, 0x1c, 0x38, 0x77, 0x3f, 0xd0, 0x4a, 0x1c, 0x76, 0xe5, 0x56, 0xe2, 0xec, 0x26,
	0xa6, 0x8d, 0x9a, 0xc4, 0x91, 0xed, 0x14, 0xe5, 0x7f, 0xf2, 0x83, 0x50, 0x9c, 0x38, 0xc9, 0x0a,
	0x90, 0x40, 0x5c, 0x5a, 0x8f, 0x67, 0x3c, 0xef, 0x79, 0x9e, 0x5b, 0xb0, 0x73, 0xce, 0x24, 0x0b,
	0xd4, 0x27, 0x32, 0xd5, 0x97, 0x98, 0xbe, 0xde, 0x33, 0xb6, 0x4f, 0xe8, 0x4a, 0xc1, 0x5d, 0xf1,
	0x6d, 0x25, 0xe3, 0x94, 0x0a, 0x49, 0xd2, 0xbc, 0x16, 0xfa, 0x29, 0x8c, 0xae, 0x12, 0x16, 0x1e,
	0xd1, 0x12, 0xcc, 0x03, 0x25, 0x11, 0xe5, 0x9e, 0x31, 0x33, 0xe6, 0xf6, 0xe5, 0xf3, 0x5a, 0x20,
	0x02, 0x45, 0xdf, 0x29, 0x0a, 0x37, 0x12, 0xf4, 0x09, 0x1c, 0xc9, 0x49, 0x26, 0x48, 0x28, 0x63,
	0x96, 0x09, 0xef, 0x7c, 0x36, 0xe8, 0x1f, 0xd9, 0x76, 0x1c, 0x7e, 0x24, 0xf4, 0x7f, 0x18, 0x60,
	0xf7, 0x0c, 0x51, 0x00, 0xc3, 0xaa, 0xa3, 0xa6, 0xe6, 0x34, 0xa8, 0xdb, 0x0d, 0x74, 0xbb, 0xc1,
	0x56, 0xb7, 0x8b, 0x95, 0x0e, 0xbd, 0x02, 0x33, 0x2b, 0xd2, 0x1d, 0xe5, 0xde, 0xf9, 0xcc, 0x98,
	0x0f, 0x70, 0x83, 0xd0, 0x0b, 0x18, 0x65, 0x24, 0x0b, 0xa9, 0x37, 0x98, 0x19, 0x73, 0x07, 0xd7,
	0x00, 0x4d, 0x61, 0x92, 0x73, 0x7a, 0xba, 0x23, 0xe2, 0xe0, 0x0d, 0x15, 0xd1, 0xe2, 0x8a, 0x0b,
	0x0b, 0xce, 0x15, 0x37, 0xaa, 0x39, 0x8d, 0xd1, 0x0a, 0x2c, 0x11, 0xef, 0x33, 0x22, 0x0b, 0x4e,
	0x3d, 0x53, 0xb5, 0x76, 0xa1, 0xef, 0xb6, 0xd1, 0x04, 0xee, 0x34, 0xbe, 0x00, 0xbb, 0x77, 0x67,
	0xf4, 0x01, 0x80, 0xe5, 0x94, 0x93, 0x3a, 0x1c, 0x43, 0x85, 0xd3, 0x1a, 0xdc, 0x6b, 0x06, 0xf7,
	0x44, 0xd5, 0x91, 0xd6, 0x4e, 0xe7, 0xf9, 0x9b, 0x9a, 0x3d, 0x91, 0xbf, 0x05, 0xab, 0xf5, 0x42,
	0xef, 0xc1, 0x64, 0xf9, 0xb6, 0xcc, 0xeb, 0x28, 0x9f, 0x5e, 0xbe, 0xfc, 0xa5, 0x5c, 0x45, 0xe2,
	0x46, 0x84, 0x3c, 0x18, 0xe7, 0xa4, 0x4c, 0x18, 0x89, 0x54, 0x90, 0x0e, 0xd6, 0xd0, 0x67, 0xe0,
	0xde, 0xd0, 0x9c, 0x89, 0x58, 0x76, 0xe6, 0x4b, 0x98, 0x70, 0x1a, 0xd2, 0xf8, 0xd4, 0xbe, 0x8e,
	0x67, 0xda, 0x7e, 0x1d, 0x45, 0x9c, 0x0a, 0x81, 0x5b, 0x41, 0x35, 0x22, 0x92, 0xb2, 0x22, 0x93,
	0x7a, 0x44, 0x35, 0xaa, 0xf6, 0x45, 0x99, 0xee, 0x58, 0xa2, 0x66, 0x64, 0xe1, 0x06, 0xf9, 0x09,
	0x5c, 0x7c, 0x8d, 0xe5, 0x21, 0xe2, 0xe4, 0x7b, 0x57, 0xf1, 0x2d, 0x98, 0x82, 0x66, 0xd1, 0x9f,
	0xeb, 0x35, 0xf4, 0x3f, 0x57, 0x5b, 0xc2, 0xb8, 0xb1, 0x40, 0x33, 0xb0, 0x49, 0xbd, 0xbc, 0x2a,
	0x65, 0x9d, 0x9b, 0x83, 0xfb, 0x5b, 0xfe, 0x2d, 0x58, 0x0f, 0xc5, 0x2e, 0x89, 0xc3, 0x2f, 0xb4,
	0x44, 0x6f, 0x60, 0x28, 0xbb, 0x7c, 0x91, 0x6e, 0xe8, 0x9a, 0x97, 0xb9, 0x64, 0x2a, 0x5c, 0xc5,
	0x23, 0x17, 0x06, 0x47, 0x5a, 0x36, 0xb1, 0x56, 0x4b, 0xff, 0x33, 0xc0, 0x03, 0x8f, 0x4f, 0x44,
	0xd2, 0xe3, 0x7f, 0xf9, 0xdc, 0x83, 0xd5, 0xbe, 0x84, 0xbf, 0xb6, 0x71, 0xc0, 0xe0, 0x8d, 0x89,
	0xc1, 0x2b, 0x24, 0x9a, 0xdf, 0x88, 0x21, 0x16, 0x0b, 0x78, 0xf2, 0xe8, 0x79, 0x20, 0x1b, 0xc6,
	0xcd, 0xf0, 0xdd, 0x33, 0xe4, 0xc0, 0x44, 0x0f, 0xc6, 0x35, 0x16, 0xef, 0x00, 0x3a, 0x6f, 0x64,
	0xc1, 0xe8, 0xf6, 0xfa, 0x66, 0xb3, 0x76, 0xcf, 0xd0, 0x18, 0x06, 0x78, 0xb3, 0x76, 0x8d, 0x6a,
	0x51, 0xed, 0x9c, 0xef, 0xea, 0x3f, 0x9f, 0x8f, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x7d,
	0x21, 0xea, 0x92, 0x04, 0x00, 0x00,
}
