// Code generated by protoc-gen-go.
// source: github.com/crazybits/x/blockchain/blockchain.proto
// DO NOT EDIT!

/*
Package blockchain is a generated protocol buffer package.

It is generated from these files:
	github.com/crazybits/x/blockchain/blockchain.proto

It has these top-level messages:
	Block
	BlockHeader
	Transaction
	Operation
	DepositOperation
	WithdrawOperation
	TransferOperation
	Address
	Account
	BlockchainInfo
*/
package blockchain

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import crypto "github.com/crazybits/x/crypto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OperationType int32

const (
	OperationType_UNDEFINED OperationType = 0
	OperationType_Deposit   OperationType = 1
	OperationType_Withdraw  OperationType = 2
	OperationType_Transfer  OperationType = 3
)

var OperationType_name = map[int32]string{
	0: "UNDEFINED",
	1: "Deposit",
	2: "Withdraw",
	3: "Transfer",
}
var OperationType_value = map[string]int32{
	"UNDEFINED": 0,
	"Deposit":   1,
	"Withdraw":  2,
	"Transfer":  3,
}

func (x OperationType) String() string {
	return proto.EnumName(OperationType_name, int32(x))
}
func (OperationType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Block struct {
	Header       *BlockHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Transactions []*Transaction `protobuf:"bytes,2,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type BlockHeader struct {
	Time      *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
	Number    int64                      `protobuf:"varint,2,opt,name=number" json:"number,omitempty"`
	Nance     []byte                     `protobuf:"bytes,3,opt,name=nance,proto3" json:"nance,omitempty"`
	PrevHash  []byte                     `protobuf:"bytes,4,opt,name=prevHash,proto3" json:"prevHash,omitempty"`
	CurrHash  []byte                     `protobuf:"bytes,5,opt,name=currHash,proto3" json:"currHash,omitempty"`
	Signature *crypto.Signature          `protobuf:"bytes,6,opt,name=signature" json:"signature,omitempty"`
	Signee    *crypto.PublicKey          `protobuf:"bytes,7,opt,name=signee" json:"signee,omitempty"`
}

func (m *BlockHeader) Reset()                    { *m = BlockHeader{} }
func (m *BlockHeader) String() string            { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()               {}
func (*BlockHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BlockHeader) GetTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *BlockHeader) GetSignature() *crypto.Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *BlockHeader) GetSignee() *crypto.PublicKey {
	if m != nil {
		return m.Signee
	}
	return nil
}

type Transaction struct {
	Operations []*Operation        `protobuf:"bytes,1,rep,name=operations" json:"operations,omitempty"`
	Signatures []*crypto.Signature `protobuf:"bytes,2,rep,name=signatures" json:"signatures,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Transaction) GetOperations() []*Operation {
	if m != nil {
		return m.Operations
	}
	return nil
}

func (m *Transaction) GetSignatures() []*crypto.Signature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

type Operation struct {
	Type    OperationType `protobuf:"varint,1,opt,name=type,enum=blockchain.OperationType" json:"type,omitempty"`
	Payload []byte        `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Operation) Reset()                    { *m = Operation{} }
func (m *Operation) String() string            { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()               {}
func (*Operation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DepositOperation struct {
	Receiver *Address `protobuf:"bytes,1,opt,name=receiver" json:"receiver,omitempty"`
	Amount   int64    `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
	Symbol   string   `protobuf:"bytes,3,opt,name=symbol" json:"symbol,omitempty"`
}

func (m *DepositOperation) Reset()                    { *m = DepositOperation{} }
func (m *DepositOperation) String() string            { return proto.CompactTextString(m) }
func (*DepositOperation) ProtoMessage()               {}
func (*DepositOperation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DepositOperation) GetReceiver() *Address {
	if m != nil {
		return m.Receiver
	}
	return nil
}

type WithdrawOperation struct {
	Sender *Address `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	Amount int64    `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
	Symbol string   `protobuf:"bytes,3,opt,name=symbol" json:"symbol,omitempty"`
}

func (m *WithdrawOperation) Reset()                    { *m = WithdrawOperation{} }
func (m *WithdrawOperation) String() string            { return proto.CompactTextString(m) }
func (*WithdrawOperation) ProtoMessage()               {}
func (*WithdrawOperation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *WithdrawOperation) GetSender() *Address {
	if m != nil {
		return m.Sender
	}
	return nil
}

type TransferOperation struct {
	Sender   *Address `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	Receiver *Address `protobuf:"bytes,2,opt,name=receiver" json:"receiver,omitempty"`
	Symbo    string   `protobuf:"bytes,3,opt,name=symbo" json:"symbo,omitempty"`
	Amount   int64    `protobuf:"varint,4,opt,name=amount" json:"amount,omitempty"`
}

func (m *TransferOperation) Reset()                    { *m = TransferOperation{} }
func (m *TransferOperation) String() string            { return proto.CompactTextString(m) }
func (*TransferOperation) ProtoMessage()               {}
func (*TransferOperation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TransferOperation) GetSender() *Address {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *TransferOperation) GetReceiver() *Address {
	if m != nil {
		return m.Receiver
	}
	return nil
}

type Address struct {
	AddressByte []byte `protobuf:"bytes,1,opt,name=addressByte,proto3" json:"addressByte,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type Account struct {
	Name     string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	PubicKey *crypto.PublicKey `protobuf:"bytes,2,opt,name=pubicKey" json:"pubicKey,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Account) GetPubicKey() *crypto.PublicKey {
	if m != nil {
		return m.PubicKey
	}
	return nil
}

type BlockchainInfo struct {
	Height            uint64 `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	CurrentBlockHash  []byte `protobuf:"bytes,2,opt,name=currentBlockHash,proto3" json:"currentBlockHash,omitempty"`
	PreviousBlockHash []byte `protobuf:"bytes,3,opt,name=previousBlockHash,proto3" json:"previousBlockHash,omitempty"`
}

func (m *BlockchainInfo) Reset()                    { *m = BlockchainInfo{} }
func (m *BlockchainInfo) String() string            { return proto.CompactTextString(m) }
func (*BlockchainInfo) ProtoMessage()               {}
func (*BlockchainInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto.RegisterType((*Block)(nil), "blockchain.Block")
	proto.RegisterType((*BlockHeader)(nil), "blockchain.BlockHeader")
	proto.RegisterType((*Transaction)(nil), "blockchain.Transaction")
	proto.RegisterType((*Operation)(nil), "blockchain.Operation")
	proto.RegisterType((*DepositOperation)(nil), "blockchain.DepositOperation")
	proto.RegisterType((*WithdrawOperation)(nil), "blockchain.WithdrawOperation")
	proto.RegisterType((*TransferOperation)(nil), "blockchain.TransferOperation")
	proto.RegisterType((*Address)(nil), "blockchain.Address")
	proto.RegisterType((*Account)(nil), "blockchain.Account")
	proto.RegisterType((*BlockchainInfo)(nil), "blockchain.BlockchainInfo")
	proto.RegisterEnum("blockchain.OperationType", OperationType_name, OperationType_value)
}

func init() { proto.RegisterFile("github.com/crazybits/x/blockchain/blockchain.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 634 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x54, 0x5d, 0x6f, 0xd3, 0x3c,
	0x18, 0x7d, 0xd3, 0xef, 0x3e, 0xed, 0xa6, 0xd6, 0xef, 0x80, 0xd0, 0x1b, 0xaa, 0x5c, 0x8d, 0x8d,
	0x25, 0x62, 0x88, 0x2b, 0xae, 0x36, 0x6d, 0xb0, 0x09, 0x34, 0x90, 0x29, 0xe2, 0xda, 0x49, 0xbd,
	0x26, 0xa2, 0x8d, 0x23, 0xdb, 0xd9, 0x08, 0x97, 0xfc, 0x11, 0x7e, 0x2a, 0x28, 0xb6, 0x93, 0x78,
	0x6c, 0x20, 0xe0, 0xaa, 0x3e, 0x3e, 0xa7, 0xcf, 0x79, 0xbe, 0x1c, 0x38, 0x5c, 0x25, 0x32, 0xce,
	0x43, 0x3f, 0x62, 0x9b, 0x20, 0xe2, 0xe4, 0x4b, 0x11, 0x26, 0x52, 0x04, 0x9f, 0x83, 0x70, 0xcd,
	0xa2, 0x4f, 0x51, 0x4c, 0x92, 0xd4, 0x3a, 0xfa, 0x19, 0x67, 0x92, 0x21, 0x68, 0x6e, 0x66, 0x8f,
	0x56, 0x8c, 0xad, 0xd6, 0x34, 0x50, 0x4c, 0x98, 0x5f, 0x06, 0x32, 0xd9, 0x50, 0x21, 0xc9, 0x26,
	0xd3, 0xe2, 0xd9, 0xde, 0x2f, 0x0c, 0x22, 0x5e, 0x64, 0x92, 0x99, 0x1f, 0xad, 0xf5, 0x72, 0xe8,
	0x1e, 0x97, 0xa1, 0x51, 0x00, 0xbd, 0x98, 0x92, 0x25, 0xe5, 0xae, 0x33, 0x77, 0x76, 0x47, 0x87,
	0x0f, 0x7c, 0x2b, 0x09, 0x25, 0x39, 0x53, 0x34, 0x36, 0x32, 0xf4, 0x02, 0xc6, 0x92, 0x93, 0x54,
	0x90, 0x48, 0x26, 0x2c, 0x15, 0x6e, 0x6b, 0xde, 0xfe, 0xf9, 0x6f, 0x8b, 0x86, 0xc7, 0x37, 0xc4,
	0xde, 0x77, 0x07, 0x46, 0x56, 0x50, 0xe4, 0x43, 0xa7, 0xac, 0xc2, 0x78, 0xcf, 0x7c, 0x5d, 0xa2,
	0x5f, 0x95, 0xe8, 0x2f, 0xaa, 0x12, 0xb1, 0xd2, 0xa1, 0xfb, 0xd0, 0x4b, 0xf3, 0x4d, 0x48, 0xb9,
	0xdb, 0x9a, 0x3b, 0xbb, 0x6d, 0x6c, 0x10, 0xda, 0x81, 0x6e, 0x4a, 0xd2, 0x88, 0xba, 0xed, 0xb9,
	0xb3, 0x3b, 0xc6, 0x1a, 0xa0, 0x19, 0x0c, 0x32, 0x4e, 0xaf, 0xce, 0x88, 0x88, 0xdd, 0x8e, 0x22,
	0x6a, 0x5c, 0x72, 0x51, 0xce, 0xb9, 0xe2, 0xba, 0x9a, 0xab, 0x30, 0x0a, 0x60, 0x28, 0x92, 0x55,
	0x4a, 0x64, 0xce, 0xa9, 0xdb, 0x53, 0xa9, 0x4d, 0x7d, 0xd3, 0xbe, 0xf7, 0x15, 0x81, 0x1b, 0x0d,
	0x7a, 0x0c, 0xbd, 0x12, 0x50, 0xea, 0xf6, 0x6f, 0xaa, 0xdf, 0xe5, 0xe1, 0x3a, 0x89, 0x5e, 0xd3,
	0x02, 0x1b, 0x81, 0x77, 0x0d, 0x23, 0xab, 0x3d, 0xe8, 0x39, 0x00, 0xcb, 0x28, 0x27, 0xba, 0x97,
	0x8e, 0xea, 0xe5, 0x3d, 0xbb, 0x97, 0x6f, 0x2b, 0x16, 0x5b, 0x42, 0xf4, 0x14, 0xa0, 0x76, 0xaf,
	0x46, 0x70, 0x47, 0x8a, 0x96, 0xc8, 0x5b, 0xc0, 0xb0, 0x8e, 0x85, 0x0e, 0xa0, 0x23, 0x8b, 0x4c,
	0xf7, 0x7d, 0xfb, 0xf0, 0xe1, 0x9d, 0x86, 0x8b, 0x22, 0xa3, 0x58, 0xc9, 0x90, 0x0b, 0xfd, 0x8c,
	0x14, 0x6b, 0x46, 0x96, 0xaa, 0xef, 0x63, 0x5c, 0x41, 0x4f, 0xc0, 0xe4, 0x84, 0x66, 0x4c, 0x24,
	0xb2, 0x09, 0x1e, 0xc0, 0x80, 0xd3, 0x88, 0x26, 0x57, 0xf5, 0x52, 0xfd, 0x6f, 0x1b, 0x1c, 0x2d,
	0x97, 0x9c, 0x0a, 0x81, 0x6b, 0x51, 0x39, 0x55, 0xb2, 0x61, 0x79, 0x2a, 0xab, 0xa9, 0x6a, 0x54,
	0xde, 0x8b, 0x62, 0x13, 0xb2, 0xb5, 0x1a, 0xeb, 0x10, 0x1b, 0xe4, 0x65, 0x30, 0xfd, 0x98, 0xc8,
	0x78, 0xc9, 0xc9, 0x75, 0xe3, 0xba, 0x0f, 0x3d, 0x41, 0xd3, 0xe5, 0xef, 0x3d, 0x8d, 0xe4, 0xaf,
	0x1d, 0xbf, 0x39, 0x30, 0x55, 0x63, 0xbb, 0xa4, 0xfc, 0x1f, 0x2d, 0xed, 0xae, 0xb4, 0xfe, 0xa4,
	0x2b, 0x3b, 0xd0, 0x55, 0xee, 0x26, 0x15, 0x0d, 0xac, 0xcc, 0x3b, 0x76, 0xe6, 0xde, 0x3e, 0xf4,
	0x4d, 0x08, 0x34, 0x87, 0x11, 0xd1, 0xc7, 0xe3, 0x42, 0xea, 0x19, 0x8f, 0xb1, 0x7d, 0xe5, 0xbd,
	0x81, 0xfe, 0x51, 0x14, 0xa9, 0x8a, 0x11, 0x74, 0x52, 0x62, 0x5e, 0xe0, 0x10, 0xab, 0x33, 0x3a,
	0x80, 0x41, 0x96, 0x87, 0x6a, 0x6f, 0x4d, 0xaa, 0x77, 0x2c, 0x74, 0x2d, 0xf1, 0xbe, 0x3a, 0xb0,
	0x7d, 0x5c, 0x57, 0x72, 0x9e, 0x5e, 0xaa, 0x2c, 0x63, 0x9a, 0xac, 0x62, 0xa9, 0xe2, 0x76, 0xb0,
	0x41, 0x68, 0x0f, 0x26, 0xe5, 0x2b, 0xa3, 0xa9, 0xd4, 0x5f, 0x81, 0xf2, 0xf5, 0xe9, 0x8d, 0xba,
	0x75, 0x8f, 0x9e, 0xc0, 0xb4, 0x7c, 0xad, 0x09, 0xcb, 0x45, 0x23, 0xd6, 0xef, 0xfb, 0x36, 0xb1,
	0xf7, 0x0a, 0xb6, 0x6e, 0x6c, 0x2e, 0xda, 0x82, 0xe1, 0x87, 0x8b, 0x93, 0xd3, 0x97, 0xe7, 0x17,
	0xa7, 0x27, 0x93, 0xff, 0xd0, 0x08, 0xfa, 0x66, 0x51, 0x27, 0x0e, 0x1a, 0xc3, 0xa0, 0x5a, 0xa0,
	0x49, 0xab, 0x44, 0xd5, 0x6c, 0x27, 0xed, 0xb0, 0xa7, 0x3e, 0x3e, 0xcf, 0x7e, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x80, 0x50, 0x4c, 0xd4, 0xaf, 0x05, 0x00, 0x00,
}
