// Code generated by protoc-gen-go.
// source: crypto_proto.proto
// DO NOT EDIT!

/*
Package crypto is a generated protocol buffer package.

It is generated from these files:
	crypto_proto.proto

It has these top-level messages:
	PublicKey
	Privatekey
	Signature
*/
package crypto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CryptoType int32

const (
	CryptoType_ECDSA CryptoType = 0
	CryptoType_RSA   CryptoType = 1
	CryptoType_DSA   CryptoType = 2
)

var CryptoType_name = map[int32]string{
	0: "ECDSA",
	1: "RSA",
	2: "DSA",
}
var CryptoType_value = map[string]int32{
	"ECDSA": 0,
	"RSA":   1,
	"DSA":   2,
}

func (x CryptoType) String() string {
	return proto.EnumName(CryptoType_name, int32(x))
}
func (CryptoType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PublicKey struct {
	Type CryptoType `protobuf:"varint,1,opt,name=type,enum=crypto.CryptoType" json:"type,omitempty"`
	Key  []byte     `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *PublicKey) Reset()                    { *m = PublicKey{} }
func (m *PublicKey) String() string            { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()               {}
func (*PublicKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Privatekey struct {
	Type CryptoType `protobuf:"varint,1,opt,name=type,enum=crypto.CryptoType" json:"type,omitempty"`
	Key  []byte     `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *Privatekey) Reset()                    { *m = Privatekey{} }
func (m *Privatekey) String() string            { return proto.CompactTextString(m) }
func (*Privatekey) ProtoMessage()               {}
func (*Privatekey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Signature struct {
	Type CryptoType `protobuf:"varint,1,opt,name=type,enum=crypto.CryptoType" json:"type,omitempty"`
	R    []byte     `protobuf:"bytes,2,opt,name=r,proto3" json:"r,omitempty"`
	S    []byte     `protobuf:"bytes,3,opt,name=s,proto3" json:"s,omitempty"`
}

func (m *Signature) Reset()                    { *m = Signature{} }
func (m *Signature) String() string            { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()               {}
func (*Signature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*PublicKey)(nil), "crypto.PublicKey")
	proto.RegisterType((*Privatekey)(nil), "crypto.Privatekey")
	proto.RegisterType((*Signature)(nil), "crypto.Signature")
	proto.RegisterEnum("crypto.CryptoType", CryptoType_name, CryptoType_value)
}

func init() { proto.RegisterFile("crypto_proto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0x2e, 0xaa, 0x2c,
	0x28, 0xc9, 0x8f, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x03, 0x93, 0x42, 0x6c, 0x10, 0x31, 0x25,
	0x57, 0x2e, 0xce, 0x80, 0xd2, 0xa4, 0x9c, 0xcc, 0x64, 0xef, 0xd4, 0x4a, 0x21, 0x35, 0x2e, 0x96,
	0x92, 0xca, 0x82, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x21, 0x3d, 0x88, 0x1a, 0x3d,
	0x67, 0x30, 0x15, 0x52, 0x59, 0x90, 0x1a, 0x04, 0x96, 0x17, 0x12, 0xe0, 0x62, 0xce, 0x4e, 0xad,
	0x94, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x09, 0x02, 0x31, 0x95, 0xdc, 0xb8, 0xb8, 0x02, 0x8a, 0x32,
	0xcb, 0x12, 0x4b, 0x52, 0xb3, 0x29, 0x32, 0xc7, 0x9f, 0x8b, 0x33, 0x38, 0x33, 0x3d, 0x2f, 0xb1,
	0xa4, 0xb4, 0x28, 0x95, 0x68, 0x63, 0x78, 0xb8, 0x18, 0x8b, 0xa0, 0x86, 0x30, 0x16, 0x81, 0x78,
	0xc5, 0x12, 0xcc, 0x10, 0x5e, 0xb1, 0x96, 0x26, 0x17, 0x17, 0x42, 0xbd, 0x10, 0x27, 0x17, 0xab,
	0xab, 0xb3, 0x4b, 0xb0, 0xa3, 0x00, 0x83, 0x10, 0x3b, 0x17, 0x73, 0x50, 0xb0, 0xa3, 0x00, 0x23,
	0x88, 0x01, 0x12, 0x61, 0x4a, 0x62, 0x03, 0x87, 0x8c, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xf6,
	0xcb, 0xb3, 0xff, 0x2f, 0x01, 0x00, 0x00,
}
